codecov:
  require_ci_to_pass: false
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: "5%"
    patch:
      default:
        target: auto
        threshold: "5%"
flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: "5%"
      - type: patch
        target: "90%"
        threshold: "5%"
  individual_flags:
    - name: frontend
    - name: backend
