-- Dummy schema for linters and formatters

-- create table scores (
-- 	id bigint generated by default as identity primary key,
-- 	name text constraint length check (char_length(name) <= 255),
-- 	value float
-- );
